image:
  repository: registry1.dso.mil/ironbank/jetstack/cert-manager-controller
  tag: "v1.15.0"

cainjector:
  image:
    repository: registry1.dso.mil/ironbank/jetstack/cert-manager-cainjector
    tag: "v1.15.0"

webhook:
  image:
    repository: registry1.dso.mil/ironbank/jetstack/cert-manager-webhook
    tag: "v1.15.0"

startupapicheck:
  image:
    repository: registry1.dso.mil/ironbank/jetstack/cert-manager-ctl
    tag: "v1.14.2"
  podLabels:
    sidecar.istio.io/inject: "false"
