variables:
  - name: FLAVOR
    default: "upstream"

tasks:
  - name: package
    description: "Create pkg flavor of Cert-Manager"
    inputs:
      options:
        description: "For setting deploy time variables and flags"
    actions:
      - cmd: uds zarf package create --flavor=${FLAVOR} --confirm ${{ .inputs.options }} --no-progress
