tasks:
  - name: package
    description: "Deploy pkg flavor of Cert-Manager"
    inputs:
      options:
        description: "For setting zarf vars"
    actions:
      - cmd: uds zarf package deploy zarf-package-*.zst ${{ .inputs.options }} --confirm --no-progress
