tasks:
  - name: cert-manager-pkg-flavor
    description: "Deploy pkg flavor of Cert-Manager"
    actions:
      - cmd: zarf package deploy zarf-package-*.zst --components=deploy-custom-manifests --set CERT_MANAGER_MANIFESTS=${CERT_MANAGER_MANIFESTS} --set CERT_MANAGER_VALUES=${CERT_MANAGER_VALUES} --confirm
