variables:
  - name: TARGET_REPO
    default: ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: "The version of the packages to build"
    # x-release-please-start-version
    default: "0.1.3"
    # x-release-please-end

tasks:
  - name: package
    actions:
      - cmd: uds zarf package publish zarf-package-cert-manager-*-${VERSION}.tar.zast oci://${TARGET_REPO}
