variables:
  - name: TARGET_REPO
    default: ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: "The version of the packages to build"
    # x-release-please-start-version
    default: "0.2.0"
    # x-release-please-end

  - name: FLAVOR
    default: upstream

tasks:
  - name: package
    description: "publish cert-manager package"
    actions:
      - cmd: |
          echo "Publishing package to ${TARGET_REPO}"
           uds zarf package publish zarf-package-cert-manager-amd64-${VERSION}.tar.zst oci://${TARGET_REPO}

          # dont publish arm64 for registry1 since IB images are only amd64
          if [ "${FLAVOR}" != "registry1" ]; then
            uds zarf package publish zarf-package-cert-manager-arm64-${VERSION}.tar.zst oci://${TARGET_REPO}
          fi
