tasks:
  - name: core-istio
    actions:
      - description: "Deploy uds istio core bundle"
        # renovate: datasource=github-tags depName=defenseunicorns/uds-core versioning=semver
        cmd: uds deploy ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core-slim-dev:0.24.0 --confirm --no-progress
