tasks:
  - name: create-k3d-cluster
    actions:
      - description: "Create the k3d cluster"
        # renovate: datasource=github-tags depName=defenseunicorns/uds-k3d versioning=semver
        cmd: "zarf package deploy oci://defenseunicorns/uds-k3d:0.1.12-multi --confirm"

      - description: "Initialize the cluster with Zarf"
        # renovate: datasource=github-tags depName=defenseunicorns/init versioning=semver
        cmd: "zarf package deploy oci://defenseunicorns/init:v0.31.4-${UDS_ARCH} --confirm --components=git-server"
