tasks:
  - name: k3d-no-istio
    actions:
      - description: "Create the k3d cluster"
        # renovate: datasource=github-tags depName=defenseunicorns/uds-k3d versioning=semver
        cmd: uds zarf package deploy oci://defenseunicorns/uds-k3d:0.7.0 --confirm --no-progress

      - description: "Initialize the cluster with Zarf"
        # renovate: datasource=github-tags depName=defenseunicorns/init versioning=semver
        cmd: uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/init:v0.34.0 --confirm --no-progress

  - name: core-istio
    actions:
      - description: "Deploy uds istio core bundle"
        # renovate: datasource=github-tags depName=defenseunicorns/uds-core versioning=semver
        cmd: uds deploy ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core-slim-dev:0.22.2 --confirm --no-progress
