tasks:
  - name: uds-core
    actions:
      - description: "Deploy uds-core bundle"
        # renovate: datasource=github-tags depName=defenseunicorns/uds/bundles/k3d-core versioning=semver
        cmd: uds deploy oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core:0.7.1-amd64 --confirm
