apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  network:
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        podSelector:
          app.kubernetes.io/name: cainjector
        remoteGenerated: KubeAPI
