name: Publish

# Will remove before merge and make it only tags
on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Package Flavor
        run: |
          ZARF_ARCHITECTURE=amd64  uds run create-pkg --set FLAVOR=${{ matrix.flavor }}
          ZARF_ARCHITECTURE=arm64  uds run create-pkg --set FLAVOR=${{ matrix.flavor }}

      - name: Deploy amd64 pkg
        run: uds run deploy-pkg --set deploy_options="--components=deploy-custom-manifests --set CUSTOM_MANIFESTS=./examples/deploy-custom-manifests.yaml"

      - name: Publish Zarf Package Flavor
        run: uds run publish-pkg
