name: Publish

# Will remove before merge and make it only tags
on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          install-k3d: false
          download-init-package: false

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Registry1
        uses: docker/login-action@v3
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Create Package Flavor
        run: uds run create-pkg-flavor --set FLAVOR=${{ matrix.flavor }}

      - name: Publish Zarf Package Flavor
        run: uds run publish-pkg-flavor

      - name: Publish Zarf Skeleton
        run: zarf package publish . oci://ghcr.io/defenseunicorns/packages
        working-directory: ${{ inputs.working_dir }}
        timeout-minutes: 60
