name: Test Package

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

permissions:
  contents: read

jobs:
  on-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Setup Cluster, Create Package, Deploy Package
        run: uds run default --set flavor=${{ matrix.flavor }}

      - name: Remove Package from k3d cluster
        run: uds run remove:package

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@172a905901cb9bd76d096d2850bf31af5c5a4fa1 # v0.8.0
        with:
          suffix: test-${{ matrix.flavor }}
