name: Test k3d Package

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install-no-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          install-k3d: true
          download-init-package: true

      - name: Login to Registry1
        uses: docker/login-action@v3
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Setup Cluster
        run: uds run setup-cluster-no-istio

      - name: Create Pkg Flavor
        run: uds run create-pkg-flavor --set FLAVOR=${{ matrix.flavor }}

      - name: Deploy Pkg Flavor
        run: uds run deploy-pkg-flavor --set CERT_MANAGER_VALUES=./.github/ci-values/values-override.yaml --set CERT_MANAGER_MANIFESTS=./examples/deploy-custom-manifests.yaml

      - name: Remove Package from k3d cluster
        run: uds run remove-pkg-flavor

  test-clean-install-with-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          install-k3d: true
          download-init-package: true

      - name: Login to Registry1
        uses: docker/login-action@v3
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Setup Cluster
        run: uds run setup-cluster-istio

      - name: Create Pkg Flavor
        run: uds run create-pkg-flavor --set FLAVOR=${{ matrix.flavor }}

      - name: Deploy Pkg Flavor
        run: uds run deploy-pkg-flavor --set CERT_MANAGER_VALUES=./.github/ci-values/values-override.yaml --set CERT_MANAGER_MANIFESTS=./examples/deploy-custom-manifests.yaml --set CONFIGURE_FOR_ISTIO=true

      - name: Remove Package from k3d cluster
        run: uds run remove-pkg-flavor
